function changetoUSA() {
    document.getElementById("nationname").innerHTML = "United States of America"
    document.getElementById("nationpara1").innerHTML = "America is a country slowly sliding into ruin. She stayed out of the Great War, despite President Roosevelt and his Progressive Party’s desire to project American values on the world stage, and saw unprecedented economic growth during the 1920s. However, everything came apart in 1929. Calvin Coolidge’s laissez faire approach to the stock market  inadvertently caused the greatest depression America and the world had ever seen."
    document.getElementById("nationpara2").innerHTML = "The ensuing years saw the situation rapidly worsen, as the White House refused to intervene and the nations of the world simply turned to Germany. The Socialist Party of America, once at the fringe of national politics, surged into the political vacuum caused by the depression, appealing to hundreds of thousands of disenfranchised workers. The 1932 elections were some of the most bitter elections in history, but ultimately, the Progressive Party with Henry Wallace and Franklin Delano Roosevelt won on a platform promising strong economic recovery and protecting the people from the brunt of the depression."
    document.getElementById("nationpara3").innerHTML = "They have summarily failed to deliver, as the dreams of overzealous politicians crashed headfirst into reality. Now, every move is critical- socialist agitation is at an all time high, and many military leaders and politicians are beginning to meet in secret. All it would take is one spark to bring to an end the grand experiment in democracy.”"
    document.getElementById("nationpara4").innerHTML = ""
    document.getElementById("nationpara5").innerHTML = ""
    document.getElementById("nationpara6").innerHTML = ""
    document.getElementById("nationpara7").innerHTML = ""
    document.getElementById("nationpara8").innerHTML = ""
    document.getElementById("nationflag").src = "img/flag/USA.png"
}
function changetoFRA() {
    document.getElementById("nationname").innerHTML = "French Republic"
    document.getElementById("nationpara1").innerHTML = "At the outbreak of the Great War the French people were burning with revanchism against Germany, the memory of the defeat against Germany and the loss of Alsace still haunting France."
    document.getElementById("nationpara2").innerHTML = "The Great War turned out to be far more brutal and prolonged than the French could have imagined, millions of Frenchmen died in the gridlocked hell of the trenches. By 1917 France was exhausted and stood virtually alone against Germany, following several suicidal offensives, a wave of mutinies swept the military that completely broke the French war machine. Fortunately for France, German intelligence completely failed to pick up on these mutinies and no German offensives were ordered. The mutiny continued to spiral out of control, affecting all layers of French government, society and the military. Calls for peace and armistice became wide spread across France, however, those in charge of the government and the military realized that an armistice with Germany would mean total humiliation and occupation, as such they refused to accept these calls and continued on in hope of British or American intervention."
    document.getElementById("nationpara3").innerHTML = "Finally, in 1918, France's soldiers were finished with the war and the government. They formed a soldier's council which quickly found allies in France's radical left-wing movements. The soldiers council stormed government buildings across France in a brief and bloody coup. Days later, a Fourth French Republic was declared and an armistice with Germany was quickly issued. The French were surprised to learn that the Germans were just as desperate for peace as themselves, and a seemingly fair treaty was formed. Alsace will be split between German and French rule, although it will be demilitarized, all colonial possessions will be returned to their pre-war state and a period of demobilization would begin immediately."
    document.getElementById("nationpara4").innerHTML = "During the 1920's and early 1930's, the French Popular Front, a collection of left-wing parties, would come to dominate politics. The military would also play a massive role in politics, their exploits in the 1918 coup making them a renowned force to be feared by politicians across the nation. As the interwar dragged on the presence of the military would only serve to complicate politics. The ability of generals to veto any of the government's decisions and do as they pleased made them hated across all levels of the Republic, however, intelligent politicians would make use of the military's power to further their own interests. Fortunately for the politicians, the military was for the most part preoccupied during the 20's with putting down minor colonial insurrections that had arisen from the instability of 1918."
    document.getElementById("nationpara5").innerHTML = "As of 1936 French politics has become radicalized, a string of far-right and far-left parties have only increased in popularity. Hatred for Germany and fear of another Great War have led to an unhealthy change in French society and politics. The far-right believe France was cheated out of a victory and humiliated by the inability to regain Alsace, these right wing radicals have found allies in the military old guard, the aristocrats and the Catholics, allowing their popularity to skyrocket during the early 1930's. On the other hand, the radical left has been able to gain considerable influence in the government and holds physical power in politics as well as over the general populace."
    document.getElementById("nationpara6").innerHTML = ""
    document.getElementById("nationpara7").innerHTML = ""
    document.getElementById("nationpara8").innerHTML = ""
    document.getElementById("nationflag").src = "img/flag/FRA.png"
}
function changetoGER() {
    document.getElementById("nationname").innerHTML = "German Empire"
    document.getElementById("nationpara1").innerHTML = "The German Empire stands as a relatively young nation even compared to many of the new world, only having been formed in 1849, Germany wasted no time in asserting it's place amongst it's European brethren, as it established colonies throughout the globe. Tragedy struck on the 27th of March 1843 as Prussian King Friedrich Wilhelm the IV died an untimely death. In the wake of this, his brother, King Wilhelm the first took up the title of King and in 1849 accepted the Frankfurter constitution which would allow the German states to federalize with a degree of autonomy. After the now infamous Franco-German war of 1870, the French province of Alsace-Lorraine was ceded to the Kaiserreich. This was the first real storm the Empire faced, and it weathered it well. Ultimately, however, this agreement would lead to even more human suffering, for in 1914, the French, still bitter from their defeat at the hand of the Germans, declared war once again on them."
    document.getElementById("nationpara2").innerHTML = "For two long, hard years the German army stood, until at the end of those two years, Austrian reinforcements poured in to replace the by now weak and demoralized Germans. But for all the suffering the war had brought with it, in the end very little changed. Germany, however, was allowed to keep Alsace-Lorraine, but this was not without it's setbacks. At some time between 1919 and 1939, the Alsatian people were to hold a referendum to decide which country they would belong to, and the region was demilitarized. Although on a strategic level this was a stalemate, this was a huge blow to the German national spirit."
    document.getElementById("nationpara3").innerHTML = "The Kaiser was unfortunately forced to abdicate, and his widely unpopular and authoritarian leaning child, Wilhelm III, took up the mantle. Faced with an ultimatum from his generals, abdicate or face a coup, he made the sane decision and resigned, and thus crowned his son as Kaiser."
    document.getElementById("nationpara4").innerHTML = "In 1936, Kaiser Friedrich IV rules over a country weary of his familys name and reeling from the personal losses of the Great War and economic crash following the American Great Collapse. As the colonial empire starts to chip away the resources and sanity of the Government, the German Empire is toeing the line between chaos and true unity."
    document.getElementById("nationpara5").innerHTML = ""
    document.getElementById("nationpara6").innerHTML = ""
    document.getElementById("nationpara7").innerHTML = ""
    document.getElementById("nationpara8").innerHTML = ""
    document.getElementById("nationflag").src = "img/flag/GER.png"
}
function changetoHUN() {
    document.getElementById("nationname").innerHTML = "Hungarian Federation"
    document.getElementById("nationpara1").innerHTML = "In 1848 under the leadership of Lajos Kossuth, Hungary rose up against the Habsburg Empire, in 1849 the Hungarian revolution brought the Empire crashing down ending hundreds of years of Austrian dominance. Out of the ashes the Hungarian Federation was born, the Federation would come to dominate the former Habsburg lands, however, unlike the Habsburgs, Hungary brought the democratic ideals of its revolution to the region, bringing about a period of peace and prosperity. Together with Bohemia, Venice and Austria, Hungary formed the Duna-Paktum, a defensive alliance that would ensure protection from the expansionist empires that encircled them."
    document.getElementById("nationpara2").innerHTML = "In 1914 the Duna-Paktum, in accordance to their alliance with Germany against Russia, joined the Great War, proving itself a competent fighting force on the Eastern and Italian Fronts. With 1936 just beginning Hungarian politics is divided into 3 main ways of thought, the '47ers, '48ers and '49ers. The '47ers are conservatives who wish to reform Hungary into a monarchy while still incorporating the revolutions democratic ideals. The '48ers are the mainstream ideology, they follow a moderate liberalism and the April Laws set out by Kossuth in 1848, these laws sought to modernize Hungary and continue to be adapted to fit Hungary's modern circumstances. Lastly, the '49ers are a more radical offshoot of the '48ers, they follow Kossuth's teachings religiously and wish to bring about radical liberal reforms to the Federation."
    document.getElementById("nationpara3").innerHTML = "The Pax Hungarica has lasted almost 2 decades, however, in the south and east the Serbian and Romania nationalists grow bolder with each day, sending incursions into the Federation in vain attempts to reclaim their ethnic territories. Many fear another war in the Balkans is inevitable. To make matters worse, the German economic giant that keeps the Duna-Paktum afloat has begun to groan and crack under its own weight. The Paktum grows restless, Hungarian dominance has started to take its toll on many member nations who now seek to separate...  "
    document.getElementById("nationpara4").innerHTML = "The next years will be crucial for the Federation. "
    document.getElementById("nationpara5").innerHTML = ""
    document.getElementById("nationpara6").innerHTML = ""
    document.getElementById("nationpara7").innerHTML = ""
    document.getElementById("nationpara8").innerHTML = ""
    document.getElementById("nationflag").src = "img/flag/HUN.png"
}
function changetoCHI() {
    document.getElementById("nationname").innerHTML = "Republic of China"
    document.getElementById("nationpara1").innerHTML = "In 1850 the self-proclaimed brother of Jesus Christ, Hong Xiuquan, led a massive rebellion against the Manchu dominated Qing dynasty. The Taiping Heavenly Kingdom was declared by Hong and a brutal civil war ensued taking tens of millions of lives and spanning across China. In 1855 the Qing capital of Beijing would fall to the Taiping and with it the entire Qing dynasty would collapse. The Heavenly Kingdom briefly ruled over the coastal regions of China before it too collapsed following the death of Hong. In the ashes many Taiping and Qing generals took land for themselves, with no central government left to confront them China descended into warlordism, civil war and instability. "
    document.getElementById("nationpara2").innerHTML = "From their concessions the European powers watched on at the senseless bloodshed. In an effort to secure their position against the unstable warlords, the European powers chose to intervene, seizing more land and more concessions for their empires. "
    document.getElementById("nationpara3").innerHTML = "As a result of the Taiping victory, China was changed forever. The old Manchu rulers lost all their power and for the first time in over 4000 years China was without a ruling dynasty. Christianity and western values became vastly more popular in China, although a staunch anti-European attitude overtook the population."
    document.getElementById("nationpara4").innerHTML = "War and unchecked dictatorships dominated China up until the 1890's, by this time a new generation of Chinese had arisen and with them came calls for revolution and reform. The Chinese democratic revolution began when the soldiers and students of China's major coastal cities ousted the local warlords and introduced a new democratic system, based on a combination of American and British systems. The Revive China Society under Sun Yat-Sen came to dominate the leading party of the new Chinese Republic. The revolution began to spread further into China and many warlords voluntarily joined the new Republic, however, many warlords held out resulting in further wars spanning into the 1920's. The emerging Chinese Republic lacked any allies, the European powers only wished to exploit China and could not be trusted, while the rest of Asia was too weak and under strong influence from Europe. However, China soon found an ally in Germany, they held common enemies in Russia, France and Britain. Over the 1920's and early 1930's China would experience rapid modernization and westernization from their strong exposure to Germany."
    document.getElementById("nationpara5").innerHTML = "As of 1936 China has developed into a capable regional power in Asia, their influence has begun to creep into Korea and down into India, already lighting the flames of democratic revolution in Nepal. Jingoism has come to define Chinese policy since the end of the warlord era, the Chinese people have had enough of European domination and call for an end to all concessions and the complete unification of China. Sun Yat-sen, the president of China since the Republics inception, has grown old and can no capably lead the nation. The clock now ticks towards war with the colonialist powers and the death of Sun, the future of a united and prosperous China will be decided in the coming conflict, a conflict that will tear the world apart for a second time in the century."
    document.getElementById("nationpara6").innerHTML = "With the collapse of the Qing Dynasty and continued decline of China throughout the warlord period, European businesses could expand unchecked across the Chinese mainland. In secret France, Russia and Britain agreed to divide China amongst themselves, the north would be under Russia's sphere, the south would be under France's sphere and the east under Britain's sphere. With the growing European influence in China, the European nations demanded concessions and dispatched military and organizational attaches to their new outposts in China. Soon many of the Southern warlords would become mere puppets of France and Britain, eventually integrating into the larger colonial states of British China and the French Far East in a similar fashion to the British Raj."
    document.getElementById("nationpara7").innerHTML = ""
    document.getElementById("nationpara8").innerHTML = ""
    document.getElementById("nationflag").src = "img/flag/CHI.png"
}
function sendtodisc() {
    window.open("https://aotrmod.org/discord");
}
function sendtoreddit() {
    window.open("https://aotrmod.org/reddit");
}